### ISSUE TITLE
Issue Using HSQL

### ISSUE THREAD

**Issue by SteveFeldman** [thedunster/parking-heatmap#4]
Looks like you have to enable "Google Maps Geocoding API" otherwise it won't work...Something you should add to the README.

**Comment by thedunster** [comment]
Hi Steve,

What did you do to enable geocoding api? 

Thanks,
Dan

**Comment by thedunster** [comment]
I think I understand the comment. You mean to enable it in the Google Developer console? I will update the read me for that. If that is not, what you meant please let me know.

**Comment by SteveFeldman** [comment]
That's what I meant....
